/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface AppealInput {
    status: string;
    appealReason: string;
    patientId: string;
    claimId: string;
    denialId: string;
    notes: string;
}
export interface RCMStats {
    avgResolutionDays: number;
    denialRate: number;
    totalAR: number;
    pendingPreAuths: bigint;
    approvalRate: number;
    totalPaidValue: number;
    claimsByStatus: Array<[string, bigint]>;
    totalClaimsValue: number;
}
export type ClinicalDocResult = {
    __kind__: "ok";
    ok: string;
} | {
    __kind__: "err";
    err: string;
};
export interface PaymentRecord {
    id: string;
    transactionRef: string;
    reconciledAt: bigint;
    patientId: string;
    createdAt: bigint;
    claimId: string;
    settlementStatus: string;
    updatedAt: bigint;
    paymentDate: string;
    patientName: string;
    paymentMode: string;
    discrepancyRemarks: string;
    paidAmount: string;
    payerName: string;
    approvedAmount: string;
    billedAmount: string;
}
export interface DoctorMasterRequest {
    name: string;
    registrationNumber: string;
    isActive: boolean;
    email: string;
    phone: string;
    department: string;
    specialisation: string;
}
export interface TpaMasterRequest {
    code: string;
    name: string;
    contactPerson: string;
    isActive: boolean;
    email: string;
    tpaType: string;
    phone: string;
}
export interface WardMaster {
    id: string;
    name: string;
    createdAt: bigint;
    ratePerDay: string;
    totalBeds: bigint;
    isActive: boolean;
    updatedAt: bigint;
    wardType: string;
}
export interface DocChecklistItem {
    submitted: boolean;
    required: boolean;
    docName: string;
}
export type ClaimResult = {
    __kind__: "ok";
    ok: string;
} | {
    __kind__: "err";
    err: string;
};
export interface TpaMaster {
    id: string;
    code: string;
    name: string;
    createdAt: bigint;
    contactPerson: string;
    isActive: boolean;
    email: string;
    updatedAt: bigint;
    tpaType: string;
    phone: string;
}
export interface Patient {
    id: string;
    dob: string;
    documents: Array<DocumentRef>;
    eligibilityStatus: string;
    name: string;
    createdAt: bigint;
    createdBy: string;
    eligibilityCheckedAt: bigint;
    abhaId: string;
    address: string;
    gender: string;
    phone: string;
    policyStart: string;
    payerName: string;
    payerType: string;
    policyNumber: string;
    policyEnd: string;
}
export interface DoctorMaster {
    id: string;
    name: string;
    createdAt: bigint;
    registrationNumber: string;
    isActive: boolean;
    email: string;
    updatedAt: bigint;
    phone: string;
    department: string;
    specialisation: string;
}
export type RegisterResult = {
    __kind__: "ok";
    ok: string;
} | {
    __kind__: "err";
    err: string;
};
export interface DocumentRef {
    documentId: string;
    docType: string;
}
export interface RegisterRequest {
    dob: string;
    name: string;
    abhaId: string;
    address: string;
    gender: string;
    phone: string;
    policyStart: string;
    payerName: string;
    payerType: string;
    policyNumber: string;
    policyEnd: string;
}
export interface IcdMaster {
    id: string;
    code: string;
    createdAt: bigint;
    description: string;
    isActive: boolean;
    updatedAt: bigint;
    category: string;
}
export type PreAuthResult = {
    __kind__: "ok";
    ok: string;
} | {
    __kind__: "err";
    err: string;
};
export interface ClaimRecord {
    id: string;
    procedureDetails: string;
    packageName: string;
    status: string;
    rejectionRemarks: string;
    timelineEvents: Array<ClaimTimelineEvent>;
    settlementDate: string;
    patientId: string;
    admissionDate: string;
    createdAt: bigint;
    icdCode: string;
    claimType: string;
    updatedAt: bigint;
    schemeType: string;
    documentChecklist: Array<DocChecklistItem>;
    patientName: string;
    preAuthId: string;
    payerName: string;
    dischargeDate: string;
    approvedAmount: string;
    diagnosisName: string;
    billedAmount: string;
    packageCode: string;
}
export interface IcdMasterRequest {
    code: string;
    description: string;
    isActive: boolean;
    category: string;
}
export interface WardMasterRequest {
    name: string;
    ratePerDay: string;
    totalBeds: bigint;
    isActive: boolean;
    wardType: string;
}
export type PaymentResult = {
    __kind__: "ok";
    ok: string;
} | {
    __kind__: "err";
    err: string;
};
export interface ClaimTimelineEvent {
    stage: string;
    notes: string;
    timestamp: bigint;
}
export interface PreAuthRequest {
    packageName: string;
    patientId: string;
    schemeType: string;
    documentChecklist: Array<DocChecklistItem>;
    requestedAmount: string;
    patientName: string;
    payerName: string;
    expectedTATHours: bigint;
    diagnosisName: string;
    packageCode: string;
}
export interface Appeal {
    id: string;
    status: string;
    appealReason: string;
    patientId: string;
    createdAt: bigint;
    submittedAt?: bigint;
    claimId: string;
    denialId: string;
    notes: string;
    resolvedAt?: bigint;
}
export interface QueryMessage {
    fromTPA: boolean;
    message: string;
    timestamp: bigint;
}
export type MasterResult = {
    __kind__: "ok";
    ok: string;
} | {
    __kind__: "err";
    err: string;
};
export type DenialResult = {
    __kind__: "ok";
    ok: string;
} | {
    __kind__: "err";
    err: string;
};
export interface DenialRecord {
    id: string;
    packageName: string;
    status: string;
    alertSent: boolean;
    rejectionRemarks: string;
    patientId: string;
    createdAt: bigint;
    resubmittedAt: bigint;
    claimId: string;
    rootCauseNotes: string;
    updatedAt: bigint;
    schemeType: string;
    rejectionCategory: string;
    patientName: string;
    payerName: string;
    resolvedAt: bigint;
    packageCode: string;
}
export interface DenialRequest {
    packageName: string;
    rejectionRemarks: string;
    patientId: string;
    claimId: string;
    rootCauseNotes: string;
    schemeType: string;
    rejectionCategory: string;
    patientName: string;
    payerName: string;
    packageCode: string;
}
export interface ClinicalDocRequest {
    doctorNotes: string;
    packageNames: Array<string>;
    patientId: string;
    dischargeSummary: string;
    documentChecklist: Array<ClinicalDocChecklistItem>;
    patientName: string;
    packageCodes: Array<string>;
}
export interface ClinicalDocRecord {
    id: string;
    doctorNotes: string;
    status: string;
    packageNames: Array<string>;
    patientId: string;
    dischargeSummary: string;
    createdAt: bigint;
    updatedAt: bigint;
    documentChecklist: Array<ClinicalDocChecklistItem>;
    patientName: string;
    packageCodes: Array<string>;
}
export interface ClinicalDocChecklistItem {
    submitted: boolean;
    required: boolean;
    docName: string;
    docType: string;
    packageCode: string;
}
export interface HospitalMasterRequest {
    nabhNumber: string;
    code: string;
    name: string;
    contactPerson: string;
    isActive: boolean;
    email: string;
    address: string;
    phone: string;
    rohiniId: string;
}
export interface PreAuthRecord {
    id: string;
    packageName: string;
    status: string;
    patientId: string;
    submittedAt: bigint;
    updatedAt: bigint;
    schemeType: string;
    documentChecklist: Array<DocChecklistItem>;
    queries: Array<QueryMessage>;
    requestedAmount: string;
    patientName: string;
    payerName: string;
    expectedTATHours: bigint;
    remarks: string;
    diagnosisName: string;
    packageCode: string;
}
export interface PaymentRequest {
    transactionRef: string;
    patientId: string;
    claimId: string;
    paymentDate: string;
    patientName: string;
    paymentMode: string;
    discrepancyRemarks: string;
    paidAmount: string;
    payerName: string;
    approvedAmount: string;
    billedAmount: string;
}
export interface ClaimRequest {
    procedureDetails: string;
    packageName: string;
    patientId: string;
    admissionDate: string;
    icdCode: string;
    claimType: string;
    schemeType: string;
    documentChecklist: Array<DocChecklistItem>;
    patientName: string;
    preAuthId: string;
    payerName: string;
    dischargeDate: string;
    approvedAmount: string;
    diagnosisName: string;
    billedAmount: string;
    packageCode: string;
}
export type AppealResult = {
    __kind__: "ok";
    ok: Appeal;
} | {
    __kind__: "err";
    err: string;
};
export interface HospitalMaster {
    id: string;
    nabhNumber: string;
    code: string;
    name: string;
    createdAt: bigint;
    contactPerson: string;
    isActive: boolean;
    email: string;
    updatedAt: bigint;
    address: string;
    phone: string;
    rohiniId: string;
}
export interface AgingAR {
    bucket61to90: Array<ClaimRecord>;
    bucket91plus: Array<ClaimRecord>;
    totalOutstanding: number;
    bucket0to30: Array<ClaimRecord>;
    bucket31to60: Array<ClaimRecord>;
}
export interface backendInterface {
    addDocument(patientId: string, documentId: string, docType: string): Promise<boolean>;
    addQueryResponse(id: string, message: string, fromTPA: boolean): Promise<boolean>;
    createAppeal(input: AppealInput): Promise<AppealResult>;
    createClaim(req: ClaimRequest): Promise<ClaimResult>;
    createClinicalDoc(req: ClinicalDocRequest): Promise<ClinicalDocResult>;
    createDenial(req: DenialRequest): Promise<DenialResult>;
    createDoctor(req: DoctorMasterRequest): Promise<MasterResult>;
    createHospital(req: HospitalMasterRequest): Promise<MasterResult>;
    createIcd(req: IcdMasterRequest): Promise<MasterResult>;
    createPayment(req: PaymentRequest): Promise<PaymentResult>;
    createPreAuth(req: PreAuthRequest): Promise<PreAuthResult>;
    createTpa(req: TpaMasterRequest): Promise<MasterResult>;
    createWard(req: WardMasterRequest): Promise<MasterResult>;
    deleteDoctor(id: string): Promise<boolean>;
    deleteHospital(id: string): Promise<boolean>;
    deleteIcd(id: string): Promise<boolean>;
    deleteTpa(id: string): Promise<boolean>;
    deleteWard(id: string): Promise<boolean>;
    getAgingAR(): Promise<AgingAR>;
    getAppealById(id: string): Promise<Appeal | null>;
    getAppeals(): Promise<Array<Appeal>>;
    getAppealsByDenialId(denialId: string): Promise<Array<Appeal>>;
    getClaimById(id: string): Promise<ClaimRecord | null>;
    getClaims(): Promise<Array<ClaimRecord>>;
    getClaimsByPatient(patientId: string): Promise<Array<ClaimRecord>>;
    getClaimsByPreAuth(preAuthId: string): Promise<Array<ClaimRecord>>;
    getClaimsByStatus(status: string): Promise<Array<ClaimRecord>>;
    getClinicalDocById(id: string): Promise<ClinicalDocRecord | null>;
    getClinicalDocs(): Promise<Array<ClinicalDocRecord>>;
    getClinicalDocsByPatient(patientId: string): Promise<Array<ClinicalDocRecord>>;
    getClinicalDocsByStatus(status: string): Promise<Array<ClinicalDocRecord>>;
    getDenialById(id: string): Promise<DenialRecord | null>;
    getDenials(): Promise<Array<DenialRecord>>;
    getDenialsByClaimId(claimId: string): Promise<Array<DenialRecord>>;
    getDenialsByStatus(status: string): Promise<Array<DenialRecord>>;
    getDoctors(): Promise<Array<DoctorMaster>>;
    getHospitals(): Promise<Array<HospitalMaster>>;
    getIcds(): Promise<Array<IcdMaster>>;
    getPatientByAbhaId(abhaId: string): Promise<Patient | null>;
    getPatientById(id: string): Promise<Patient | null>;
    getPatients(): Promise<Array<Patient>>;
    getPatientsByStatus(status: string): Promise<Array<Patient>>;
    getPaymentById(id: string): Promise<PaymentRecord | null>;
    getPayments(): Promise<Array<PaymentRecord>>;
    getPaymentsByClaimId(claimId: string): Promise<Array<PaymentRecord>>;
    getPaymentsByPatient(patientId: string): Promise<Array<PaymentRecord>>;
    getPaymentsByStatus(status: string): Promise<Array<PaymentRecord>>;
    getPreAuthById(id: string): Promise<PreAuthRecord | null>;
    getPreAuths(): Promise<Array<PreAuthRecord>>;
    getPreAuthsByPatient(patientId: string): Promise<Array<PreAuthRecord>>;
    getPreAuthsByStatus(status: string): Promise<Array<PreAuthRecord>>;
    getRCMStats(): Promise<RCMStats>;
    getTpas(): Promise<Array<TpaMaster>>;
    getWards(): Promise<Array<WardMaster>>;
    registerPatient(req: RegisterRequest): Promise<RegisterResult>;
    searchPatients(searchTerm: string): Promise<Array<Patient>>;
    updateAppealStatus(id: string, status: string, notes: string): Promise<AppealResult>;
    updateClaimStatus(id: string, status: string, remarks: string): Promise<boolean>;
    updateClinicalDoc(id: string, doctorNotes: string, dischargeSummary: string, documentChecklist: Array<ClinicalDocChecklistItem>, status: string): Promise<boolean>;
    updateDenialStatus(id: string, status: string, rootCauseNotes: string, resubmitted: boolean): Promise<boolean>;
    updateDoctor(id: string, req: DoctorMasterRequest): Promise<boolean>;
    updateEligibility(id: string, status: string): Promise<boolean>;
    updateHospital(id: string, req: HospitalMasterRequest): Promise<boolean>;
    updateIcd(id: string, req: IcdMasterRequest): Promise<boolean>;
    updatePaymentStatus(id: string, settlementStatus: string, paidAmount: string, transactionRef: string, discrepancyRemarks: string): Promise<boolean>;
    updatePreAuthStatus(id: string, status: string, remarks: string): Promise<boolean>;
    updateTpa(id: string, req: TpaMasterRequest): Promise<boolean>;
    updateWard(id: string, req: WardMasterRequest): Promise<boolean>;
}
import type { Appeal as _Appeal, AppealResult as _AppealResult, ClaimRecord as _ClaimRecord, ClaimResult as _ClaimResult, ClinicalDocRecord as _ClinicalDocRecord, ClinicalDocResult as _ClinicalDocResult, DenialRecord as _DenialRecord, DenialResult as _DenialResult, MasterResult as _MasterResult, Patient as _Patient, PaymentRecord as _PaymentRecord, PaymentResult as _PaymentResult, PreAuthRecord as _PreAuthRecord, PreAuthResult as _PreAuthResult, RegisterResult as _RegisterResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addDocument(arg0: string, arg1: string, arg2: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.addDocument(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addDocument(arg0, arg1, arg2);
            return result;
        }
    }
    async addQueryResponse(arg0: string, arg1: string, arg2: boolean): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.addQueryResponse(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addQueryResponse(arg0, arg1, arg2);
            return result;
        }
    }
    async createAppeal(arg0: AppealInput): Promise<AppealResult> {
        if (this.processError) {
            try {
                const result = await this.actor.createAppeal(arg0);
                return from_candid_AppealResult_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createAppeal(arg0);
            return from_candid_AppealResult_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async createClaim(arg0: ClaimRequest): Promise<ClaimResult> {
        if (this.processError) {
            try {
                const result = await this.actor.createClaim(arg0);
                return from_candid_ClaimResult_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createClaim(arg0);
            return from_candid_ClaimResult_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async createClinicalDoc(arg0: ClinicalDocRequest): Promise<ClinicalDocResult> {
        if (this.processError) {
            try {
                const result = await this.actor.createClinicalDoc(arg0);
                return from_candid_ClinicalDocResult_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createClinicalDoc(arg0);
            return from_candid_ClinicalDocResult_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async createDenial(arg0: DenialRequest): Promise<DenialResult> {
        if (this.processError) {
            try {
                const result = await this.actor.createDenial(arg0);
                return from_candid_DenialResult_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createDenial(arg0);
            return from_candid_DenialResult_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async createDoctor(arg0: DoctorMasterRequest): Promise<MasterResult> {
        if (this.processError) {
            try {
                const result = await this.actor.createDoctor(arg0);
                return from_candid_MasterResult_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createDoctor(arg0);
            return from_candid_MasterResult_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async createHospital(arg0: HospitalMasterRequest): Promise<MasterResult> {
        if (this.processError) {
            try {
                const result = await this.actor.createHospital(arg0);
                return from_candid_MasterResult_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createHospital(arg0);
            return from_candid_MasterResult_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async createIcd(arg0: IcdMasterRequest): Promise<MasterResult> {
        if (this.processError) {
            try {
                const result = await this.actor.createIcd(arg0);
                return from_candid_MasterResult_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createIcd(arg0);
            return from_candid_MasterResult_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async createPayment(arg0: PaymentRequest): Promise<PaymentResult> {
        if (this.processError) {
            try {
                const result = await this.actor.createPayment(arg0);
                return from_candid_PaymentResult_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createPayment(arg0);
            return from_candid_PaymentResult_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async createPreAuth(arg0: PreAuthRequest): Promise<PreAuthResult> {
        if (this.processError) {
            try {
                const result = await this.actor.createPreAuth(arg0);
                return from_candid_PreAuthResult_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createPreAuth(arg0);
            return from_candid_PreAuthResult_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async createTpa(arg0: TpaMasterRequest): Promise<MasterResult> {
        if (this.processError) {
            try {
                const result = await this.actor.createTpa(arg0);
                return from_candid_MasterResult_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createTpa(arg0);
            return from_candid_MasterResult_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async createWard(arg0: WardMasterRequest): Promise<MasterResult> {
        if (this.processError) {
            try {
                const result = await this.actor.createWard(arg0);
                return from_candid_MasterResult_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createWard(arg0);
            return from_candid_MasterResult_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteDoctor(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteDoctor(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteDoctor(arg0);
            return result;
        }
    }
    async deleteHospital(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteHospital(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteHospital(arg0);
            return result;
        }
    }
    async deleteIcd(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteIcd(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteIcd(arg0);
            return result;
        }
    }
    async deleteTpa(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteTpa(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteTpa(arg0);
            return result;
        }
    }
    async deleteWard(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteWard(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteWard(arg0);
            return result;
        }
    }
    async getAgingAR(): Promise<AgingAR> {
        if (this.processError) {
            try {
                const result = await this.actor.getAgingAR();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAgingAR();
            return result;
        }
    }
    async getAppealById(arg0: string): Promise<Appeal | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getAppealById(arg0);
                return from_candid_opt_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAppealById(arg0);
            return from_candid_opt_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAppeals(): Promise<Array<Appeal>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAppeals();
                return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAppeals();
            return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAppealsByDenialId(arg0: string): Promise<Array<Appeal>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAppealsByDenialId(arg0);
                return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAppealsByDenialId(arg0);
            return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getClaimById(arg0: string): Promise<ClaimRecord | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getClaimById(arg0);
                return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getClaimById(arg0);
            return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getClaims(): Promise<Array<ClaimRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getClaims();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getClaims();
            return result;
        }
    }
    async getClaimsByPatient(arg0: string): Promise<Array<ClaimRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getClaimsByPatient(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getClaimsByPatient(arg0);
            return result;
        }
    }
    async getClaimsByPreAuth(arg0: string): Promise<Array<ClaimRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getClaimsByPreAuth(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getClaimsByPreAuth(arg0);
            return result;
        }
    }
    async getClaimsByStatus(arg0: string): Promise<Array<ClaimRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getClaimsByStatus(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getClaimsByStatus(arg0);
            return result;
        }
    }
    async getClinicalDocById(arg0: string): Promise<ClinicalDocRecord | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getClinicalDocById(arg0);
                return from_candid_opt_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getClinicalDocById(arg0);
            return from_candid_opt_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getClinicalDocs(): Promise<Array<ClinicalDocRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getClinicalDocs();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getClinicalDocs();
            return result;
        }
    }
    async getClinicalDocsByPatient(arg0: string): Promise<Array<ClinicalDocRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getClinicalDocsByPatient(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getClinicalDocsByPatient(arg0);
            return result;
        }
    }
    async getClinicalDocsByStatus(arg0: string): Promise<Array<ClinicalDocRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getClinicalDocsByStatus(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getClinicalDocsByStatus(arg0);
            return result;
        }
    }
    async getDenialById(arg0: string): Promise<DenialRecord | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getDenialById(arg0);
                return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDenialById(arg0);
            return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDenials(): Promise<Array<DenialRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getDenials();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDenials();
            return result;
        }
    }
    async getDenialsByClaimId(arg0: string): Promise<Array<DenialRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getDenialsByClaimId(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDenialsByClaimId(arg0);
            return result;
        }
    }
    async getDenialsByStatus(arg0: string): Promise<Array<DenialRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getDenialsByStatus(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDenialsByStatus(arg0);
            return result;
        }
    }
    async getDoctors(): Promise<Array<DoctorMaster>> {
        if (this.processError) {
            try {
                const result = await this.actor.getDoctors();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDoctors();
            return result;
        }
    }
    async getHospitals(): Promise<Array<HospitalMaster>> {
        if (this.processError) {
            try {
                const result = await this.actor.getHospitals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getHospitals();
            return result;
        }
    }
    async getIcds(): Promise<Array<IcdMaster>> {
        if (this.processError) {
            try {
                const result = await this.actor.getIcds();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getIcds();
            return result;
        }
    }
    async getPatientByAbhaId(arg0: string): Promise<Patient | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getPatientByAbhaId(arg0);
                return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPatientByAbhaId(arg0);
            return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPatientById(arg0: string): Promise<Patient | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getPatientById(arg0);
                return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPatientById(arg0);
            return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPatients(): Promise<Array<Patient>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPatients();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPatients();
            return result;
        }
    }
    async getPatientsByStatus(arg0: string): Promise<Array<Patient>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPatientsByStatus(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPatientsByStatus(arg0);
            return result;
        }
    }
    async getPaymentById(arg0: string): Promise<PaymentRecord | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getPaymentById(arg0);
                return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPaymentById(arg0);
            return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPayments(): Promise<Array<PaymentRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPayments();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPayments();
            return result;
        }
    }
    async getPaymentsByClaimId(arg0: string): Promise<Array<PaymentRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPaymentsByClaimId(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPaymentsByClaimId(arg0);
            return result;
        }
    }
    async getPaymentsByPatient(arg0: string): Promise<Array<PaymentRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPaymentsByPatient(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPaymentsByPatient(arg0);
            return result;
        }
    }
    async getPaymentsByStatus(arg0: string): Promise<Array<PaymentRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPaymentsByStatus(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPaymentsByStatus(arg0);
            return result;
        }
    }
    async getPreAuthById(arg0: string): Promise<PreAuthRecord | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getPreAuthById(arg0);
                return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPreAuthById(arg0);
            return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPreAuths(): Promise<Array<PreAuthRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPreAuths();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPreAuths();
            return result;
        }
    }
    async getPreAuthsByPatient(arg0: string): Promise<Array<PreAuthRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPreAuthsByPatient(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPreAuthsByPatient(arg0);
            return result;
        }
    }
    async getPreAuthsByStatus(arg0: string): Promise<Array<PreAuthRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPreAuthsByStatus(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPreAuthsByStatus(arg0);
            return result;
        }
    }
    async getRCMStats(): Promise<RCMStats> {
        if (this.processError) {
            try {
                const result = await this.actor.getRCMStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRCMStats();
            return result;
        }
    }
    async getTpas(): Promise<Array<TpaMaster>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTpas();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTpas();
            return result;
        }
    }
    async getWards(): Promise<Array<WardMaster>> {
        if (this.processError) {
            try {
                const result = await this.actor.getWards();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWards();
            return result;
        }
    }
    async registerPatient(arg0: RegisterRequest): Promise<RegisterResult> {
        if (this.processError) {
            try {
                const result = await this.actor.registerPatient(arg0);
                return from_candid_RegisterResult_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerPatient(arg0);
            return from_candid_RegisterResult_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async searchPatients(arg0: string): Promise<Array<Patient>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchPatients(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchPatients(arg0);
            return result;
        }
    }
    async updateAppealStatus(arg0: string, arg1: string, arg2: string): Promise<AppealResult> {
        if (this.processError) {
            try {
                const result = await this.actor.updateAppealStatus(arg0, arg1, arg2);
                return from_candid_AppealResult_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateAppealStatus(arg0, arg1, arg2);
            return from_candid_AppealResult_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateClaimStatus(arg0: string, arg1: string, arg2: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateClaimStatus(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateClaimStatus(arg0, arg1, arg2);
            return result;
        }
    }
    async updateClinicalDoc(arg0: string, arg1: string, arg2: string, arg3: Array<ClinicalDocChecklistItem>, arg4: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateClinicalDoc(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateClinicalDoc(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async updateDenialStatus(arg0: string, arg1: string, arg2: string, arg3: boolean): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateDenialStatus(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateDenialStatus(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async updateDoctor(arg0: string, arg1: DoctorMasterRequest): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateDoctor(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateDoctor(arg0, arg1);
            return result;
        }
    }
    async updateEligibility(arg0: string, arg1: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateEligibility(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateEligibility(arg0, arg1);
            return result;
        }
    }
    async updateHospital(arg0: string, arg1: HospitalMasterRequest): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateHospital(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateHospital(arg0, arg1);
            return result;
        }
    }
    async updateIcd(arg0: string, arg1: IcdMasterRequest): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateIcd(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateIcd(arg0, arg1);
            return result;
        }
    }
    async updatePaymentStatus(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updatePaymentStatus(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updatePaymentStatus(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async updatePreAuthStatus(arg0: string, arg1: string, arg2: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updatePreAuthStatus(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updatePreAuthStatus(arg0, arg1, arg2);
            return result;
        }
    }
    async updateTpa(arg0: string, arg1: TpaMasterRequest): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTpa(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTpa(arg0, arg1);
            return result;
        }
    }
    async updateWard(arg0: string, arg1: WardMasterRequest): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateWard(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateWard(arg0, arg1);
            return result;
        }
    }
}
function from_candid_AppealResult_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AppealResult): AppealResult {
    return from_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function from_candid_Appeal_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Appeal): Appeal {
    return from_candid_record_n4(_uploadFile, _downloadFile, value);
}
function from_candid_ClaimResult_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ClaimResult): ClaimResult {
    return from_candid_variant_n7(_uploadFile, _downloadFile, value);
}
function from_candid_ClinicalDocResult_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ClinicalDocResult): ClinicalDocResult {
    return from_candid_variant_n7(_uploadFile, _downloadFile, value);
}
function from_candid_DenialResult_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DenialResult): DenialResult {
    return from_candid_variant_n7(_uploadFile, _downloadFile, value);
}
function from_candid_MasterResult_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MasterResult): MasterResult {
    return from_candid_variant_n7(_uploadFile, _downloadFile, value);
}
function from_candid_PaymentResult_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PaymentResult): PaymentResult {
    return from_candid_variant_n7(_uploadFile, _downloadFile, value);
}
function from_candid_PreAuthResult_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PreAuthResult): PreAuthResult {
    return from_candid_variant_n7(_uploadFile, _downloadFile, value);
}
function from_candid_RegisterResult_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RegisterResult): RegisterResult {
    return from_candid_variant_n7(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Appeal]): Appeal | null {
    return value.length === 0 ? null : from_candid_Appeal_n3(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ClaimRecord]): ClaimRecord | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ClinicalDocRecord]): ClinicalDocRecord | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_DenialRecord]): DenialRecord | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Patient]): Patient | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_PaymentRecord]): PaymentRecord | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_PreAuthRecord]): PreAuthRecord | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: string;
    appealReason: string;
    patientId: string;
    createdAt: bigint;
    submittedAt: [] | [bigint];
    claimId: string;
    denialId: string;
    notes: string;
    resolvedAt: [] | [bigint];
}): {
    id: string;
    status: string;
    appealReason: string;
    patientId: string;
    createdAt: bigint;
    submittedAt?: bigint;
    claimId: string;
    denialId: string;
    notes: string;
    resolvedAt?: bigint;
} {
    return {
        id: value.id,
        status: value.status,
        appealReason: value.appealReason,
        patientId: value.patientId,
        createdAt: value.createdAt,
        submittedAt: record_opt_to_undefined(from_candid_opt_n5(_uploadFile, _downloadFile, value.submittedAt)),
        claimId: value.claimId,
        denialId: value.denialId,
        notes: value.notes,
        resolvedAt: record_opt_to_undefined(from_candid_opt_n5(_uploadFile, _downloadFile, value.resolvedAt))
    };
}
function from_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _Appeal;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: Appeal;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_Appeal_n3(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: string;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: string;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_vec_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Appeal>): Array<Appeal> {
    return value.map((x)=>from_candid_Appeal_n3(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
